In [5]:
import torch
import torch.nn as nn 

In [9]:
#input

toruch
inputs = torch.tensor([1.0,2.0,3.0])

In [10]:
neuron = nn.Linear(in_features = 3, out_features = 1)


In [11]:
output = neuron(inputs)

In [12]:
output

tensor([-1.8905], grad_fn=<ViewBackward0>)

In [13]:

neuron.weight

Parameter containing:
tensor([[-0.4288, -0.5008, -0.0757]], requires_grad=True)

In [14]:
neuron.bias

Parameter containing:
tensor([-0.2329], requires_grad=True)